name: 'Islandora Groups for Access Control'
description: 'Taxonomy-based group assignment for islandora.'
type: 'Access control'
install:
  - islandora_group
  - group_solr
  - private_files_adapter


